[package]
name = "lms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
ycl = { git = "https://github.com/brooks-builds/ycl", rev = "a6a472c" }
# ycl = { path = "../ycl" }
yew-router = "0.17.0"
