name: Yew Component Library
on: [push, pull_request]
jobs:
  lint:
    name: Cargo check and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: touch .env
      - name: cargo check
        run: cargo check
      - name: cargo clippy
        run: cargo clippy
      - name: check formatting
        run: cargo fmt --check

  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: touch .env
      - name: build app
        run: trunk build
      - name: run tests
        run: npx playwright test
        env:
          FRONTEND_URI: http://localhost:8082

  deploy:
    if: github.event_name == "pull_request" && github.ref_name == "main"
    name: deploy to production
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: touch .env
      - name: install prerequisites
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk
      - name: build
        run: trunk build --release
      - name: deploy
        run: aws s3 sync dist ${{ secrets.DEPLOYMENT_URI }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
