import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker';

test('test', async ({ page }) => {
  const tagName = faker.word.words(1);
  const courseTitle = faker.word.words(5);
  const longDescription = faker.lorem.sentences(5);
  const shortDescription = faker.lorem.sentence();
  const articleOneTitle = faker.word.words(3);
  const articleTwoTitle = faker.word.words(3);

  await page.goto('/');
  await page.getByRole('link', { name: 'Login or Signup' }).click();
  await page.getByLabel('Email address*').click();
  await page.getByLabel('Email address*').fill(process.env.TEST_AUTHOR_USERNAME || "");
  await page.getByLabel('Email address*').press('Tab');
  await page.getByLabel('Password*').fill(process.env.TEST_AUTHOR_PASSWORD || '');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.waitForURL(/**\/localhost**/);
  await expect(page.getByText('Welcome brooks')).toBeVisible();
  await expect(page.getByText('Author')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Brooks Builds Learning' })).toBeVisible();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Tags' }).click();
  await page.getByLabel('Tag Name').click();
  await page.getByLabel('Tag Name').fill(tagName);
  await page.getByRole('button', { name: 'Create Tag' }).click();
  await expect(page.getByRole('cell', { name: tagName })).toBeVisible();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Create Course' }).click();
  await page.getByLabel('Title').click();
  await page.getByLabel('Title').fill(courseTitle);
  await page.getByTestId('select').selectOption(tagName);
  await page.getByLabel('Long Description').click();
  await page.getByLabel('Long Description').fill(longDescription);
  await page.getByLabel('Short Description').click();
  await page.getByLabel('Short Description').fill(shortDescription);
  await page.getByRole('button', { name: 'Create Course' }).click();
  await expect(page.getByText('course created')).toBeVisible();
  await page.getByLabel('Close').click();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Create Article' }).click();
  await page.getByLabel('Title').click();
  await page.getByLabel('Title').fill(articleOneTitle);
  await page.getByLabel('Article Body').click();
  await page.getByLabel('Article Body').fill(`# ${articleOneTitle}\n\nWelcome to the course`);
  await page.getByRole('button', { name: 'Create Article' }).click();
  await expect(page.getByText('Article created')).toBeVisible();
  await page.getByLabel('Close').click();
  await page.getByLabel('Title').click();
  await page.getByLabel('Title').fill(articleTwoTitle);
  await page.getByLabel('Article Body').click();
  await page.getByLabel('Article Body').fill('# ' + articleTwoTitle + '\n\n```rust\npub fn i_am_a_function() {\n  println!("hello");\n}\n```');
  await page.getByRole('button', { name: 'Create Article' }).click();
  await expect(page.getByText('Article created')).toBeVisible();
  await page.getByLabel('Close').click();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Courses' }).click();
  await page.getByRole('link', { name: courseTitle }).click();
  await page.getByRole('link', { name: 'Course Articles' }).click();
  await page.getByRole('button', { name: articleOneTitle }).click();
  await page.getByRole('button', { name: articleTwoTitle }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('Course articles saved')).toBeVisible();
  await page.getByLabel('Close').click();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Courses' }).click();
  await page.getByRole('link', { name: courseTitle }).click();
  await expect(page.getByRole('heading', { name: courseTitle })).toBeVisible();
  await expect(page.getByText(longDescription)).toBeVisible();
  await page.getByRole('link', { name: 'Preview' }).click();
  await expect(page.getByRole('heading', { name: articleOneTitle, exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: articleTwoTitle })).toBeVisible();
  await page.getByRole('link', { name: 'logout' }).click();
  await page.locator('#navbarSupportedContent').getByRole('link', { name: 'Courses' }).click();
  await page.getByRole('link', { name: courseTitle }).click();
  await expect(page.getByRole('heading', { name: courseTitle })).toBeVisible();
  await expect(page.getByText(longDescription)).toBeVisible();
  await page.getByRole('link', { name: 'Preview' }).click();
  await expect(page.getByRole('heading', { name: articleOneTitle, exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: articleTwoTitle })).toBeVisible();
  await page.getByRole('button', { name: 'Preview the article' }).first().click();
  await expect(page.getByRole('heading', { name: articleOneTitle, exact: true })).toBeVisible();
  await expect(page.getByText('Welcome to the course')).toBeVisible();
  await page.getByRole('link', { name: 'Complete and goto next' }).click();
  await expect(page.getByRole('heading', { name: articleTwoTitle })).toBeVisible();
  await expect(page.locator('pre')).toBeVisible();
  await page.getByRole('link', { name: 'Brooks Builds Brand icon' }).click();
  await expect(page.getByRole('heading', { name: 'Brooks Builds Learning' })).toBeVisible();
});
